export const INCREMENT = "INCREMENT";
export const DELETE_ARTICLE_FROM_ID = "DELETE_ARTICLE_FROM_ID";
export const CHANGE_DATE_RANGE = "CHANGE_DATE_RANGE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";
export const ADD_COMMENT = "ADD_COMMENT";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const LOAD_ALL_ARTICLES = "LOAD_ALL_ARTICLES";
export const START = "_START";
export const SUCCESS = "_SUCCESS";
export const FAIL = "_FAIL";

export const LOAD_ARTICLE = "LOAD_ARTICLE";
export const LOAD_ARTICLE_COMMENTS = "LOAD_ARTICLE_COMMENTS";

export const LOAD_ALL_COMMENTS = "LOAD_ALL_COMMENTS";
